apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-cd-argocd-image-updater
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-image-updater-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argo-cd-argocd-image-updater
    namespace: argocd
roleRef:
  kind: Role
  name: argo-cd-argocd-image-updater
  apiGroup: rbac.authorization.k8s.io
