apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-cnpg
  namespace: cnpg
  annotations:
    "cnpg.io/skipEmptyWalArchiveCheck": "enabled"
spec:
  instances: 1
  imageName: "ghcr.io/cloudnative-pg/postgresql:15.3"
  storage:
    size: 1Gi

  resources:
    requests:
      memory: "1024Mi"
      cpu: "1000m"
    limits:
      memory: "2048Mi"
      cpu: "2000m"

  managed:
    roles:
      - name: user
        ensure: present
        login: true
        createdb: true
        passwordSecret:
          name: flowisedb
      - name: superadmin            
        ensure: present           
        login: true               
        createdb: true
        superuser: true            
        passwordSecret:
          name: superadmin-secret

  bootstrap:
    recovery:
      backup:
        name:  cluster-cnpg-backup
