apiVersion: v1
kind: Secret
metadata:
  name: superadmin-secret
  namespace: cnpg
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: "superadmin"
  password: "password_default1"
---
apiVersion: v1
kind: Secret
metadata:
  name: flowisedb
  namespace: cnpg
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: "user"
  password: "pass_default1"
