# k8s/deploy/base/apisix/patch/resource.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: ingress-apisix
spec:
  template:
    spec:
      containers:
      - name: apisix
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apisix-etcd
  namespace: ingress-apisix
spec:
  template:
    spec:
      containers:
      - name: etcd
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
