apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowise
  namespace: flowise
spec:
  template:
    spec:
      containers:
        - name: app
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3 
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
