apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name:  flowise
  namespace: flowise
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  flowise
  minReplicas: 1  # Minimum number of pods
  maxReplicas: 4  # Maximum number of pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Target 70% CPU usage
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75  # Target 75% memory usage
