apiVersion: v1
kind: PersistentVolume
metadata:
  name: flowise-pv
  namespace: flowise   
spec:
  capacity:
    storage: 10Gi   
  accessModes:
    - ReadWriteOnce  # Options: ReadWriteOnce, ReadOnlyMany, ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # Options: Retain, Recycle, Delete
  hostPath:
    path: /data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flowise-pvc
  namespace: flowise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
