apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama-pv
spec:
  capacity:
    storage: 60Gi   
  accessModes:
    - ReadWriteOnce  # Options: ReadWriteOnce, ReadOnlyMany, ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # Options: Retain, Recycle, Delete
  hostPath:
    path: /data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  pvc
  namespace: llama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
