
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama
  namespace: llama
  labels:
    app.kubernetes.io/name: "llama"
    app.kubernetes.io/instance: "llama"
    app.kubernetes.io/component: "server"
    app.kubernetes.io/part-of: "llama-sample"
    app.kubernetes.io/managed-by: "stacktic"
imagePullSecrets:
  - name: registry-credential
