apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama
  namespace: llama
spec:
  template:
    spec:
      containers:
        - name: app
          livenessProbe:
            httpGet:
              path: /api/version
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3 
          readinessProbe:
            httpGet:
              path: /api/version
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
